### PR TITLE
fix(circleci_scraper): KeyError in CircleCIClient exception handling

### PR DESCRIPTION
**Pull request by Trinaa**
## Description

- fix error handling bug where message lockups have a key error for child errors
- use `from` for exception chaining instead of a custom inner exception

- [x] This PR conforms to the [Contribution Guidelines](/CONTRIBUTING)
- [x] AI tools were used in generating this pull request

## Issues

Closes: # [ECTEEN-114](https://mozilla-hub.atlassian.net/browse/ECTEEN-114)

[ECTEEN-114]: https://mozilla-hub.atlassian.net/browse/ECTEEN-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by b4handjr** [comment]
Do you have an example of what was happening? Maybe a log output?

**Comment by Trinaa** [comment]
> Do you have an example of what was happening? Maybe a log output?

Yes indeed, I'll copy paste over from the JIRA task:
image

A way to reproduce locally could be to:
1. Undo the changes from this PR in `scripts/circleci_scraper/client.py`
2. Execute the tests in `tests/circleci_scraper/test_client.py` with `make test`

Alternative way is you could mess-up a url in `scripts/circleci_scraper/client.py`

**Comment by b4handjr** [comment]
Follow up Q: Why not add that error to the mapping, or add all of the different requests errors to it?

**Comment by Trinaa** [comment]
> Follow up Q: Why not add that error to the mapping, or add all of the different requests errors to it?

Good question, 2 reasons imo:
1. I can't be certain it will be comprehensive as we go forward, like for example if the requests library adds new types of child exception with new versions we will have this problem again.
2. We don't need the granularity, the error message we want to output is basically the same for all the child types.

**Review by b4handjr — APPROVED** [review]
r+, thanks for the explanations too.

**Pull request merged**
